### ISSUE TITLE
Certificate error for tiddly.bluelightav.eth.link

### ISSUE THREAD

**Issue by khinsen** [xmaysonnave/tiddlywiki-ipfs#2]
Access to https://tiddly.bluelightav.eth.link/ causes a certificate error in all browsers I tried. Here is the error message from Brave:
```
This server could not prove that it is tiddly.bluelightav.eth.link; its security certificate is from *.eth.link. This may be caused by a misconfiguration or an attacker intercepting your connection.
```

**Comment by xmaysonnave** [comment]
Yes. It is a common error. People who owns the eth.link tld provides the
ssl certificate however browsers do not like that at all. This wildcard
certificate is too widely opened and not restrictive enough. Ipfs companion
and metamask handle it properly though as you're redirected to an https
ipns URL with no complain.
Thanks for your report.

**Comment by khinsen** [comment]
Indeed. Content addressing makes so many security issues simply disappear.

**Comment by xmaysonnave** [comment]
I'm closing this ticket as the issue is not related to this plugin but the way EthDNS is handling their eth.link TLD. I've updated the link to https://tiddly.bluelightav.eth but Metamask is required. Plain HTTP is working though.
Thanks

**Comment by khinsen** [comment]
Sounds fine, thanks!
