### ISSUE TITLE
Use files rm and cp to update the cid of the html path

### ISSUE THREAD

**Issue by gscholer** [xmaysonnave/tiddlywiki-ipfs#56]
I use `ipfs` saver protocol, because saving to ipns is too slow. I want to update the cid of the tiddlywiki html path after the new version was add to ipfs repo, maybe a configure of the file path is suitable to update the cid?

**Comment by xmaysonnave** [comment]
Thanks for your interrest. 
AFAIK chcid is a way to update the file root cid, it isn't related to any data updates.
Not used in IPFS with TiddlyWiki.
Unavailable in ipfs-http-client ?

**Comment by gscholer** [comment]
Yes, I misunderstand what the `chcid` do, but the problem is clear:

my tiddlywiki is stored in `/tiddlywiki.html` in MFS, after I saved the new version of the wiki to ipfs, I also want to update the path `/tiddlywiki.html` pointer to the new cid, `files cp` is the right command, but which seem not have a overwrite option (https://github.com/ipfs/go-ipfs/issues/2074), so maybe first use `files rm` to remove the old path and then cp the new cid to the path `/tiddlywiki.html`.

It is best to have  a config to save the value of the tiddlywiki path.
